# Generated by Django 3.1.3 on 2020-11-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201105_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='secondary', max_length=20, verbose_name='цвет'),
        ),
    ]
